version: '2'

services:
  test-base:
    build:
      context: base
    command: "/bin/true"
    
  api-test-data:
    env_file: variables.env  
    build: 
      context: portal-api
    volumes:
    - "/var/portal-api/static"
    depends_on:
    - "test-base"

  portal-api:
    env_file: variables.env  
    image: haufelexware/wicked.portal-api:dev
    volumes_from:
    - "api-test-data"
    restart: never
